---
apiVersion: v1
kind: Pod
metadata:
  name: finservpod7
  labels:
     app: tsdata
spec:
  containers:
  - name: gettsdata
    image: jpworkshop.azurecr.io/sanjshah2001/timeseries
    tty: true

  - name: pushtsdata
    image: jpworkshop.azurecr.io/sanjshah2001/timeseries
    tty: true
